# RAG Metadata Logging
from sqlalchemy import Column, Integer, String, Text, JSON, Float
# Import Base from database.py file
from database import Base
 
class RAGLogs(Base):
    """
    SQLAlchemy model to store complete RAG pipeline metadata. This table is used for observability, debugging,
    and evaluation of the Retrieval-Augmented Generation (RAG) system.
    """
    __tablename__ = "rag_logs"
    # Unique identifier for each log entry
    id = Column(Integer, primary_key=True, index=True)
    # Session ID to track a specific user conversation
    session_id = Column(String(255))
    # Original user query/question
    query = Column(Text)
    # Final response generated by the LLM (Gemini)
    response = Column(Text)
    retrieved_docs = Column(JSON)
    similarity_scores = Column(JSON)
    # Metadata of retrieved documents
    sources = Column(JSON)
    # Time taken (in seconds) to process the full RAG pipeline
    latency = Column(Float)
